### ISSUE TITLE
error when executing ./start.sh

### ISSUE THREAD

**Issue by 4ttenu4tor** [danrl/wifi-probe#1]
+ ip link set up dev wlan1mon
+ sh wifi-probe.py wlan1mon
from: can't read /var/mail/scapy.all
from: can't read /var/mail/datetime
wifi-probe.py: 5: wifi-probe.py: import: not found
wifi-probe.py: 6: wifi-probe.py: import: not found
wifi-probe.py: 7: wifi-probe.py: import: not found
wifi-probe.py: 8: wifi-probe.py: import: not found
wifi-probe.py: 11: wifi-probe.py: DISPLAY_PROBES_MAX: not found
wifi-probe.py: 14: wifi-probe.py: TERM_RED: not found
wifi-probe.py: 15: wifi-probe.py: TERM_GREEN: not found
wifi-probe.py: 16: wifi-probe.py: TERM_YELLOW: not found
wifi-probe.py: 17: wifi-probe.py: TERM_BLUE: not found
wifi-probe.py: 18: wifi-probe.py: TERM_MAGENTA: not found
wifi-probe.py: 19: wifi-probe.py: TERM_BOLD: not found
wifi-probe.py: 20: wifi-probe.py: TERM_RESET: not found
wifi-probe.py: 21: wifi-probe.py: TERM_POS_ZERO: not found
wifi-probe.py: 24: wifi-probe.py: probes: not found
wifi-probe.py: 27: wifi-probe.py: Syntax error: "(" unexpected

**Comment by danrl** [comment]
It looks like you are missing dependencies.
I'd reach out to someone who is familiar with python.
